[package]
name = "ruby-rbs-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"
nom = "7.1.3"
# chumsky = "0.9.3"
# nom = "7.1.3"
pest = "2.7.11"
pest_derive = "2.7.11"
