// ╭──────────────╮
// │ Pest helpers │
// ╰──────────────╯
WHITESPACE = _{ " " | NEWLINE | "\t" }
COMMENT = { "#" ~ (!"#" ~ ANY)* ~ NEWLINE }

//╭─────────────────────────────────────────╮
//│ Top-level (public, all-consuming) rules │
//╰─────────────────────────────────────────╯
TypeClassInstanceName = { SOI ~ class_instance_name_type ~ EOI }
TypeAliasName = ${ SOI ~ alias_name_type ~ EOI }
TypeSingletonClassName = ${ SOI ~ class_singleton_name_type ~ EOI }
TypeInterfaceName = { SOI ~ interface_name_type ~ EOI }
TypeRecord = { SOI ~ record_type ~ EOI }
TypeTuple = { SOI ~ tuple_type ~ EOI }

LiteralString = ${ SOI ~ string_literal ~ EOI }
LiteralSymbol = ${ SOI ~ symbol_literal ~ EOI }
LiteralInteger = ${ SOI ~ integer_literal ~ EOI }

MemberMethod = { SOI ~ method_member ~ EOI }
MemberAlias = { SOI ~ alias_member ~ EOI }
MemberAttribute = { SOI ~ attribute_member ~ EOI }
MemberInclude = { SOI ~ include_member ~ EOI }
MemberExtend = { SOI ~ extend_member ~ EOI }
MemberPrepend = { SOI ~ prepend_member ~ EOI }

Declaration = { SOI ~ decl ~ EOI }

// ╭───────╮
// │ Types │
// ╰───────╯
rtype = { type_expr }

type_expr = !{ primary ~ (operation ~ primary)* }

operation = _{ union | intersection | optional }
union = { "|" }
intersection = { "&" }
optional = { "?" }

primary = _{
    class_instance_name_type
    | interface_name_type
    | alias_name_type
    | class_singleton_name_type
    | literal
    | record_type
    | tuple_type
    | type_variable
    | "(" ~ type_expr ~ ")"
    | "self"
    | "instance"
    | "class"
    | "bool"
    | "boolish"
    | "untyped"
    | "nil"
    | "top"
    | "bot"
    | "void"
    | proc_type
}

record_type = { "{" ~ single_record ~ ("," ~ single_record)* ~ "}" }
single_record = { record_name ~ ":" ~ type_expr }
record_name = { var_name }

tuple_type = { "[" ~ (type_expr ~ ("," ~ type_expr)*)? ~ "]" }

class_instance_name_type = { class_name ~ type_arguments? }
class_name = ${ module_name_inner }
module_name_inner = _{ namespace* ~ UPPERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")* }
module_name = ${ module_name_inner }

interface_name_type = { interface_name ~ type_arguments? }
interface_name = ${ namespace* ~ "_" ~ UPPERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")* }

alias_name_type = { alias_name ~ type_arguments? }
alias_name = ${ namespace* ~ LOWERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")* }

class_singleton_name_type = !{ "singleton" ~ "(" ~ class_name ~ ")" }

type_variable = ${ UPPERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")* }

namespace = ${ "::" | (namespace_name ~ "::")+ }
namespace_name = ${ UPPERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")* }

type_arguments = { "[" ~ type_expr ~ ("," ~ type_expr)* ~ "]" }

literal = ${
    string_literal
    | symbol_literal
    | integer_literal
    | "true"
    | "false"
}

string_literal = ${ double_quoted_string_literal | single_quoted_string_literal }
double_quoted_string_literal = ${ double_quote ~ double_quote_inner_str ~ double_quote }
double_quote = { "\"" }
double_quote_inner_str = @{ (!double_quote ~ ANY)* }
single_quoted_string_literal = { single_quote ~ single_quote_inner_str ~ single_quote }
single_quote = { "'" }
single_quote_inner_str = @{ (!single_quote ~ ANY)* }

symbol_literal = ${
    ":" ~ (LETTER | EMOJI | NUMBER)+ ~ (LETTER | EMOJI | NUMBER | "_")*
    | ":" ~ double_quoted_string_literal
    | ":" ~ single_quoted_string_literal
}

integer_literal = ${
    "0" ~ ("d" | "D") ~ decimal_integer_literal
    | "0" ~ ("x" | "X") ~ hexadecimal_integer_literal
    | "0" ~ "o"? ~ octal_integer_literal
    | "0" ~ ("b" | "B") ~ binary_integer_literal
    | decimal_integer_literal
}
decimal_integer_literal = ${ ASCII_DIGIT ~ (ASCII_DIGIT | "_")* }
hexadecimal_integer_literal = ${ ASCII_HEX_DIGIT ~ (ASCII_HEX_DIGIT | "_")* }
octal_integer_literal = ${ ASCII_OCT_DIGIT ~ (ASCII_OCT_DIGIT | "_")* }
binary_integer_literal = ${ ASCII_BIN_DIGIT ~ (ASCII_BIN_DIGIT | "_")* }

// ╭─────────────────────────────╮
// │ Method Types and Proc Types │
// ╰─────────────────────────────╯
method_type = {
    parameters? ~ block? ~ "->" ~ type_expr
    | "(" ~ "?" ~ ")" ~ "->" ~ type_expr
}

proc_type = {
    "^" ~ parameters? ~ self_type_binding? ~ block? ~ "->" ~ type_expr
    | "^" ~ "(" ~ "?" ~ ")" ~ "->" ~ type_expr
}

parameters = {
    "("
        ~ required_positionals?
        ~ optional_positionals?
        ~ rest_positional?
        ~ trailing_positionals?
        ~ kwargs?
    ~ ")"
}

parameter = { type_expr ~ var_name? }
required_positionals = { parameter ~ ("," ~ parameter)* }
optional_positionals = { "?" ~ parameter ~ ("," ~ "?" ~ parameter)* }
rest_positional = { "*" ~ parameter }
trailing_positionals = { parameter ~ ("," ~ parameter)* }

kwargs = {
    "**" ~ parameter
    | var_name ~ ":" ~ parameter ~ "," ~ kwargs
    | "?" ~ var_name ~ ":" ~ parameter ~ "," ~ kwargs
}

var_name = { LOWERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")* }

self_type_binding = { "[" ~ "self" ~ ":" ~ type_expr ~ "]" }

block = {
    "{" ~ parameters? ~ self_type_binding? ~ "->" ~ type_expr ~ "}"
    | "{" ~ "(" ~ "?" ~ ")" ~ "->" ~ type_expr ~ "}"
    | "?" ~ "{" ~ parameters? ~ self_type_binding? ~ "->" ~ type_expr ~ "}"
    | "?" ~ "{" ~ "(" ~ "?" ~ ")" ~ "->" ~ type_expr ~ "}"
}

// ╭─────────╮
// │ Members │
// ╰─────────╯
member = {
    ivar_member
    | method_member
    | attribute_member
    | include_member
    | extend_member
    | prepend_member
    | alias_member
    | visibility_member
}

ivar_member = {
    ivar_name ~ ":" ~ type_expr
    | "self" ~ "." ~ ivar_name ~ ":" ~ type_expr
    | cvar_name ~ ":" ~ type_expr
}

method_member = { 
    instance_method 
    | singleton_method 
    | singleton_and_instance_method 
}

instance_method = { visibility? ~ "def" ~ method_name ~ ":" ~ method_types }
singleton_method = { visibility? ~ "def" ~ "self" ~ "." ~ method_name ~ ":" ~ method_types }
singleton_and_instance_method = { visibility? ~ "def" ~ "self" ~ "?" ~ "." ~ method_name ~ ":" ~ method_types }

method_name = ${ (CASED_LETTER | "`") ~ (ASCII_ALPHANUMERIC | "_" | "`")* }
method_types = {
    method_type_parameters? ~ method_type
    | method_type_parameters? ~ method_type ~ "|" ~ method_types
    | "..."
}

method_type_parameters = { "[" ~ type_variable ~ ("," ~ type_variable)* ~ "]" }

attribute_member = {
    visibility? ~ attribute_type ~ (("self" ~ ".")? ~ method_name) ~ ("(" ~ ivar_name? ~ ")")? ~ ":" ~ type_expr
}

attribute_type = { "attr_reader" | "attr_writer" | "attr_accessor" }

include_member = {
    "include" ~ (class_name | interface_name) ~ type_arguments?
}

extend_member = {
    "extend" ~ (class_name | interface_name) ~ type_arguments?
}

prepend_member = { "prepend" ~ class_name ~ type_arguments? }

alias_member = {
    "alias" ~ method_name ~ method_name
    | "alias" ~ "self" ~ "." ~ method_name ~ "self" ~ "." ~ method_name
}

visibility_member = { visibility ~ NEWLINE }
visibility = { "public" | "private" }
ivar_name = ${ "@" ~ (CASED_LETTER | "_")+ }
cvar_name = ${ "@@" ~ CASED_LETTER+ }

// ╭──────────────╮
// │ Declarations │
// ╰──────────────╯
decl = {
    class_decl
    | module_decl
    | class_alias_decl
    | module_alias_decl
    | interface_decl
    | type_alias_decl
    | const_decl
    | global_decl
    | use_directive
}

class_decl = {
    "class" ~ class_name ~ module_type_parameters? ~ ("<" ~ class_name ~ type_arguments?)? ~ member* ~ "end"
}

module_decl = {
    "module" ~ module_name ~ module_type_parameters? ~ (":" ~ module_self_types)? ~ member* ~ "end"
}

module_self_types = {
    (class_name ~ type_arguments? | interface_name ~ type_arguments?) ~ ("," ~ module_self_types)*
}

class_alias_decl = { "class" ~ class_name ~ "=" ~ class_name }
module_alias_decl = { "module" ~ module_name ~ "=" ~ module_name }

interface_decl = {
    "interface" ~ interface_name ~ module_type_parameters? ~ interface_members* ~ "end"
}

interface_members = {
    method_member
    | include_member
    | alias_member
}

type_alias_decl = {
    "type" ~ alias_name ~ module_type_parameters? ~ "=" ~ type_expr
}

const_decl = { const_name ~ ":" ~ type_expr }
global_decl = { global_name ~ ":" ~ type_expr }

const_name = { const_name_inner+ }
const_name_inner = _{ namespace? ~ UPPERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")* }
global_name = ${ "$" ~ ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }

// ╭──────────╮
// │ Generics │
// ╰──────────╯
module_type_parameters = { "[" ~ module_type_parameter ~ ("," ~ module_type_parameter)* ~ "]" }

module_type_parameter = {
    generics_unchecked? ~ generics_variance? ~ type_variable ~ generics_bound? ~ default_type?
}

generics_bound = { "<" ~ bound_type }
bound_type = {
    class_name ~ type_arguments?
    | interface_name ~ type_arguments?
    | "singleton" ~ "(" ~ class_name ~ ")"
}

default_type = { "=" ~ type_expr }
generics_variance = { "out" | "in" }
generics_unchecked = { "unchecked" }

// ╭────────────╮
// │ Directives │
// ╰────────────╯
use_directive = { "use" ~ use_clauses }
use_clauses = { use_clause ~ ("," ~ use_clause)* }
use_clause = {
    type_name ~ ("as" ~ simple_type_name)?
    | namespace
}

type_name = { (namespace? ~ UPPERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")*) }
simple_type_name = { UPPERCASE_LETTER ~ (ASCII_ALPHANUMERIC | "_")* }

// ╭─────────────╮
// │ Annotations │
// ╰─────────────╯
annotation = {
    "%a{" ~ annotation_text ~ "}"
    | "%a(" ~ annotation_text ~ ")"
    | "%a[" ~ annotation_text ~ "]"
    | "%a|" ~ annotation_text ~ "|"
    | "%a<" ~ annotation_text ~ ">"
}

annotation_text = @{ (!("}" | ")" | "]" | "|" | ">") ~ ANY)* }
